import React, { useEffect, useState } from 'react';
import { api, fmt } from '../api';
import { useApp } from '../context';

// useApp fallback so ui components can render outside the context provider
function useAppSafe() {
  try { return useApp(); } catch { return { session: null }; }
}

// ---------- Invoice viewer (print + Save-as-PDF, fully free) ----------
// kind: 'topup' (ref), 'booking' (id), 'payout' (id), 'withdrawal' (id), 'penalty' (id)
function openPrintableInvoice(inv) {
  const money = (n) => new Intl.NumberFormat('en-PK').format(n);
  const rows = inv.items.map((it) => `<tr><td>${it.description}</td><td class="r" style="color:${it.amount < 0 ? '#b3372f' : '#182420'}">${money(it.amount)}</td></tr>`).join('');
  const w = window.open('', '_blank', 'width=760,height=900');
  if (!w) { alert('Popup blocked — please allow popups to download the PDF'); return; }
  w.document.write(`<!doctype html><html><head><title>${inv.invoice_number}</title><style>
    body{font-family:Segoe UI,Arial,sans-serif;color:#182420;padding:32px;max-width:680px;margin:auto}
    h1{color:#0a5c38;margin:0 0 4px} .muted{color:#68766f;font-size:13px}
    table{width:100%;border-collapse:collapse;margin:14px 0}
    th,td{padding:7px 10px;border-bottom:1px solid #e2e8e5;font-size:14px;text-align:left}
    th{background:#f2f5f4} .r{text-align:right}
    .total th,.total td{font-weight:700;background:#eef6f1;font-size:15px}
    .brand{display:flex;justify-content:space-between;align-items:center;border-bottom:3px solid #0e7a4a;padding-bottom:10px}
    @media print{ .noprint{display:none} }
  </style></head><body>
    <div class="brand"><div><h1>Hunar</h1><div class="muted">Verified Skill, Trusted Service: Lahore</div></div><div style="text-align:right"><b>${inv.invoice_number}</b><br><span class="muted">${new Date(inv.date).toLocaleString()}</span></div></div>
    <h2 style="font-size:17px">${inv.type} <span class="muted">· ${inv.status}</span></h2>
    <table><tr><th style="width:140px">From</th><td>${inv.from}</td></tr><tr><th>To</th><td>${inv.to}</td></tr><tr><th>Method</th><td>${inv.method}</td></tr><tr><th>Reference</th><td>${inv.reference}</td></tr></table>
    <table><thead><tr><th>Description</th><th class="r">Amount (Rs)</th></tr></thead><tbody>${rows}
      <tr><td class="muted">Subtotal</td><td class="r">${money(inv.subtotal)}</td></tr>
      ${inv.fees ? `<tr><td class="muted">Platform commission</td><td class="r" style="color:#b3372f">−${money(inv.fees)}</td></tr>` : ''}
      <tr class="total"><th>Total</th><th class="r">Rs ${money(inv.total)}</th></tr>
    </tbody></table>
    ${inv.admin_note ? `<p class="muted">Admin note: ${inv.admin_note}</p>` : ''}
    <p class="muted" style="font-size:12px">Auto-generated by Hunar Platform: please retain this invoice for your records. Support: support@hunar.pk</p>
    <p class="noprint" style="margin-top:18px"><button onclick="window.print()" style="padding:10px 22px;background:#0e7a4a;color:#fff;border:0;border-radius:8px;font-size:14px;cursor:pointer">🖨 Print / Save as PDF</button></p>
    <script>window.onload = () => setTimeout(() => window.print(), 400);</script>
  </body></html>`);
  w.document.close();
}

export function InvoiceModal({ kind, id, reference, onClose }) {
  const { session } = useAppSafe();
  const [inv, setInv] = useState(null);
  const [error, setError] = useState('');
  useEffect(() => {
    let live = true;
    const url = kind === 'topup' ? `/invoices/topup/${encodeURIComponent(reference)}`
      : kind === 'booking' ? `/invoices/booking/${id}`
      : kind === 'payout' ? `/invoices/payout/${id}`
      : kind === 'withdrawal' ? `/invoices/withdrawal/${id}`
      : `/invoices/penalty/${id}`;
    api.get(url, session?.token).then((d) => { if (live) setInv(d); }).catch((e) => { if (live) setError(e.message); });
    return () => { live = false; };
  }, [kind, id, reference, session?.token]);

  if (!kind) return null;
  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(7,20,14,.55)', zIndex: 60, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 16 }} onClick={onClose}>
      <div className="card" style={{ maxWidth: 560, width: '100%', maxHeight: '88vh', overflowY: 'auto' }} onClick={(e) => e.stopPropagation()}>
        {error && <div className="alert error">{error}</div>}
        {!inv && !error && <p className="muted">Loading invoice…</p>}
        {inv && (
          <>
            <div className="row spread">
              <h2 style={{ margin: 0 }}>🧾 {inv.invoice_number}</h2>
              <span className={`badge ${inv.status === 'completed' || inv.status === 'released' ? 'verified' : 'status'}`}>{inv.status}</span>
            </div>
            <p className="muted" style={{ marginTop: 2 }}>{inv.type} · {new Date(inv.date).toLocaleString()}</p>
            <table style={{ margin: '10px 0' }}>
              <tbody>
                <tr><th style={{ width: 130 }}>From</th><td>{inv.from}</td></tr>
                <tr><th>To</th><td>{inv.to}</td></tr>
                <tr><th>Method</th><td>{inv.method}</td></tr>
                <tr><th>Reference</th><td>{inv.reference}</td></tr>
              </tbody>
            </table>
            <table>
              <thead><tr><th>Description</th><th style={{ textAlign: 'right' }}>Amount (Rs)</th></tr></thead>
              <tbody>
                {inv.items.map((it, i) => (
                  <tr key={i}><td>{it.description}</td><td style={{ textAlign: 'right', color: it.amount < 0 ? 'var(--danger)' : undefined }}>{new Intl.NumberFormat('en-PK').format(it.amount)}</td></tr>
                ))}
                <tr><td className="muted">Subtotal</td><td style={{ textAlign: 'right' }}>{new Intl.NumberFormat('en-PK').format(inv.subtotal)}</td></tr>
                {inv.fees ? <tr><td className="muted">Platform commission</td><td style={{ textAlign: 'right', color: 'var(--danger)' }}>−{new Intl.NumberFormat('en-PK').format(inv.fees)}</td></tr> : null}
                <tr><th>Total</th><th style={{ textAlign: 'right' }}>Rs {new Intl.NumberFormat('en-PK').format(inv.total)}</th></tr>
              </tbody>
            </table>
            {inv.admin_note && <p className="muted" style={{ fontSize: 13 }}>Admin note: {inv.admin_note}</p>}
            <p className="muted" style={{ fontSize: 12 }}>Generated automatically by Hunar: please retain this invoice for your records.</p>
            <div className="row mt">
              <button className="btn small" onClick={() => window.print()} title="Print this page">🖨 Print</button>
              <button className="btn small secondary" onClick={() => openPrintableInvoice(inv)}>⬇ Download PDF</button>
              <button className="btn small danger" onClick={onClose}>Close</button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}

export function StatusBadge({ status }) {
  if (!status) return null;
  return <span className={`badge ${status}`}>{status.replaceAll('_', ' ')}</span>;
}

// Direction badge: incoming (green), outgoing (red), pending (amber)
export function DirBadge({ dir, label }) {
  const map = { in: ['in', '↑ Incoming'], out: ['out', '↓ Outgoing'], pending: ['pending', '◔ Pending'] };
  const [cls, text] = map[dir] || ['', label || ''];
  return <span className={`badge dir ${cls}`}>{label || text}</span>;
}

// Quick period selector: Latest (default) / This Week / This Month / 3 Months / All + custom range
export function periodRange(period) {
  const now = new Date();
  const to = now.toISOString().slice(0, 10);
  if (period === 'week') {
    const d = new Date(now); d.setDate(d.getDate() - 7);
    return { from: d.toISOString().slice(0, 10), to };
  }
  if (period === 'month') {
    const d = new Date(now); d.setMonth(d.getMonth() - 1);
    return { from: d.toISOString().slice(0, 10), to };
  }
  if (period === 'quarter') {
    const d = new Date(now); d.setMonth(d.getMonth() - 3);
    return { from: d.toISOString().slice(0, 10), to };
  }
  return { from: '', to: '' }; // 'all'
}

export function StatementFilters({ value, onChange, onReset }) {
  return (
    <div className="filters">
      <select value={value.direction} onChange={(e) => onChange({ ...value, direction: e.target.value, page: 1 })}>
        <option value="">All Directions</option>
        <option value="in">↑ Incoming (money in)</option>
        <option value="out">↓ Outgoing (money out)</option>
      </select>
      <select value={value.type} onChange={(e) => onChange({ ...value, type: e.target.value, page: 1 })}>
        <option value="">All Types</option>
        <option value="topup">Top-up</option>
        <option value="hold">Escrow Hold</option>
        <option value="release">Release</option>
        <option value="refund">Refund</option>
        <option value="payout">Payout</option>
        <option value="penalty">Penalty</option>
        <option value="commission">Commission</option>
        <option value="withdrawal">Withdrawal</option>
        <option value="compensation">Compensation</option>
      </select>
      <input type="date" value={value.from} onChange={(e) => onChange({ ...value, from: e.target.value, page: 1 })} title="From date" />
      <input type="date" value={value.to} onChange={(e) => onChange({ ...value, to: e.target.value, page: 1 })} title="To date" />
      <button className="btn small secondary" onClick={onReset}>Reset</button>
    </div>
  );
}

export function Pagination({ pagination, onPage }) {
  if (!pagination || pagination.total_pages <= 1) return null;
  const { page, total_pages, total } = pagination;
  return (
    <div className="pagination">
      <button className="btn small secondary" disabled={page <= 1} onClick={() => onPage(page - 1)}>‹ Prev</button>
      <span className="muted">Page {page} / {total_pages} · {total} records</span>
      <button className="btn small secondary" disabled={page >= total_pages} onClick={() => onPage(page + 1)}>Next ›</button>
    </div>
  );
}

// Full statement: summary cards + period tabs + filters + paginated ledger.
// Default view: This Week (latest records first). Admin sees all via the same component.
export function StatementView({ fetcher, title = 'Transaction History', subtitle }) {
  const [data, setData] = useState(null);
  const [period, setPeriod] = useState('week'); // latest week by default
  const [filters, setFilters] = useState(() => ({ direction: '', type: '', ...periodRange('week'), page: 1 }));
  const [error, setError] = useState('');
  const [inv, setInv] = useState(null); // { kind, id, reference }

  useEffect(() => {
    let live = true;
    fetcher(filters)
      .then((d) => { if (live) setData(d); })
      .catch((e) => { if (live) setError(e.message); });
    return () => { live = false; };
  }, [filters]);

  const applyPeriod = (p) => {
    setPeriod(p);
    setFilters((f) => ({ ...f, ...periodRange(p), page: 1 }));
  };

  const s = data?.summary;
  return (
    <>
      {error && <div className="alert error">{error}</div>}
      {s && (
        <div className="grid cols-4">
          <div className="card stat"><span className="value td-amt-in">+ {fmt(s.total_in)}</span><span className="label">Total Incoming</span><span className="hint">top-ups + refunds + payouts</span></div>
          <div className="card stat"><span className="value td-amt-out">− {fmt(s.total_out)}</span><span className="label">Total Outgoing</span><span className="hint">holds + releases + penalties</span></div>
          <div className="card stat"><span className="value" style={{ color: '#b7791f' }}>{s.pending_withdrawals ? `${s.pending_withdrawals} · ${fmt(s.pending_withdrawals_amount)}` : '0'}</span><span className="label">Processing Withdrawals</span><span className="hint">being paid out via gateway</span></div>
          <div className="card stat"><span className="value" style={{ color: s.pending_penalty > 0 ? 'var(--danger)' : 'inherit' }}>{s.pending_penalty > 0 ? fmt(s.pending_penalty) : '0'}</span><span className="label">Pending Penalty (owed)</span><span className="hint">auto-deducted from next payout</span></div>
        </div>
      )}
      <div className="card">
        <h2>{title}</h2>
        {subtitle && <p className="muted mb">{subtitle}</p>}
        <div className="filters" style={{ marginBottom: 8 }}>
          {[
            ['week', 'This Week'],
            ['month', 'This Month'],
            ['quarter', 'Last 3 Months'],
            ['all', 'All Time'],
          ].map(([key, label]) => (
            <button key={key} className={`btn small ${period === key ? '' : 'secondary'}`} onClick={() => applyPeriod(key)}>{label}</button>
          ))}
        </div>
        <StatementFilters value={filters} onChange={setFilters} onReset={() => { setPeriod('week'); setFilters({ direction: '', type: '', ...periodRange('week'), page: 1 }); }} />
        {!data && <p className="muted">Loading statement…</p>}
        {data && data.rows.length === 0 && <Empty>No transactions in this period.</Empty>}
        {data && data.rows.length > 0 && (
          <>
            <table>
              <thead>
                <tr><th>Date &amp; Time</th><th>Direction</th><th>Type</th><th>Counterparty</th><th>Booking</th><th>Service</th><th>Amount</th><th>Balance After</th><th>Invoice</th></tr>
              </thead>
              <tbody>
                {data.rows.map((t) => {
                  const dir = ['topup', 'refund', 'payout', 'compensation'].includes(t.type) ? 'in' : 'out';
                  const invKind = t.booking_id ? 'booking' : t.type === 'topup' ? 'topup' : t.type === 'payout' ? 'payout' : t.type === 'penalty' ? 'penalty' : null;
                  return (
                    <tr key={t.id}>
                      <td>{t.created_at?.slice(0, 16)}</td>
                      <td><DirBadge dir={dir} label={dir === 'in' ? 'Incoming' : 'Outgoing'} /></td>
                      <td><span className={`badge ${t.type}`}>{t.type}</span></td>
                      <td>
                        {t.counterparty_role}
                        {t.counterparty_name ? <div className="muted"><b>{t.counterparty_name}</b></div> : null}
                      </td>
                      <td className="muted">{t.booking_code || '—'}</td>
                      <td className="muted">{t.category_name || '—'}</td>
                      <td><Amt value={t.amount} dir={dir} /></td>
                      <td>{fmt(t.balance_after)}</td>
                      <td>
                        {invKind === 'topup' && t.topup_ref ? <button className="btn small secondary" onClick={() => setInv({ kind: 'topup', reference: t.topup_ref })}>🧾</button>
                          : invKind === 'penalty' && t.penalty_id ? <button className="btn small secondary" onClick={() => setInv({ kind: 'penalty', id: t.penalty_id })}>🧾</button>
                          : invKind && t.booking_id ? <button className="btn small secondary" onClick={() => setInv({ kind: invKind, id: t.booking_id })}>🧾</button>
                          : <span className="muted">—</span>}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
            <Pagination pagination={data.pagination} onPage={(p) => setFilters({ ...filters, page: p })} />
          </>
        )}
      </div>

      {inv && <InvoiceModal kind={inv.kind} id={inv.id} reference={inv.reference} onClose={() => setInv(null)} />}
    </>
  );
}

// Cancel consequence modal: exact breakdown before the user confirms cancellation
const REASONS = [
  'Kaam adhoora / ghalat hua',
  'Professional waqt par nahi aaya',
  'Professional raabta nahi kar raha',
  'Extra paisay ki demand hui',
  'Tabdeeli ke baad masla (offer/price)',
  'Property ko nuqsaan pohancha',
  'Behtari / safai ka masla',
  'Koi aur masla',
];

// Report a Problem modal — prompt() ki jagah proper form (reason dropdown + description).
// Automation-friendly: real <select>/<textarea>, label se accessible.
export function DisputeModal({ bookingCode, onSubmit, onClose, busy = false }) {
  const [reason, setReason] = useState(REASONS[0]);
  const [description, setDescription] = useState('');
  const [localError, setLocalError] = useState('');
  if (!bookingCode) return null;
  const submit = () => {
    if (description.trim().length < 10) { setLocalError('Please describe the problem in a little more detail (at least 10 characters).'); return; }
    setLocalError('');
    onSubmit({ reason, description: description.trim() });
  };
  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal card" onClick={(e) => e.stopPropagation()} role="dialog" aria-label="Report a Problem">
        <h2>⚠️ Report a Problem: Booking {bookingCode}</h2>
        <p className="muted">Your payment stays safely in escrow until an administrator reviews the case and decides the outcome.</p>
        <label htmlFor="dispute-reason">Problem kis cheez ki hai?</label>
        <select id="dispute-reason" value={reason} onChange={(e) => setReason(e.target.value)} style={{ width: '100%', marginBottom: 10 }}>
          {REASONS.map((r) => <option key={r} value={r}>{r}</option>)}
        </select>
        <label htmlFor="dispute-description">Detail (professional ko nahi, sirf admin dekhega)</label>
        <textarea
          id="dispute-description"
          rows={4}
          placeholder="Kya masla hua — kaam adhoora, raabta nahi, tabdeeli ki ghiar…"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          style={{ width: '100%' }}
        />
        {localError && <div className="alert error mt">{localError}</div>}
        <div className="row mt">
          <button className="btn danger" onClick={submit} disabled={busy}>{busy ? 'Submitting…' : 'Submit Report'}</button>
          <button className="btn secondary" onClick={onClose}>Cancel</button>
        </div>
      </div>
    </div>
  );
}

export function CancelPreviewModal({ preview, onConfirm, onClose, confirmLabel = 'Yes, Cancel Booking' }) {
  if (!preview) return null;
  const isCustomer = preview.you_are === 'customer';
  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal card" onClick={(e) => e.stopPropagation()}>
        <h2>⚠️ Cancellation Preview: Booking {preview.booking_code}</h2>
        {!preview.can_cancel && (
          <>
            <div className="alert warn">{preview.message}</div>
            <button className="btn secondary" onClick={onClose}>Close</button>
          </>
        )}
        {preview.can_cancel && (
          <>
            <p className="muted">Held (escrow) amount: <b>{fmt(preview.held_amount)}</b> · Professional accepted: <b>{preview.pro_has_accepted ? 'Yes' : 'No'}</b></p>
            {isCustomer ? (
              <table>
                <tbody>
                  <tr><td>Refund %</td><td><b>{preview.refund_percent}%</b></td></tr>
                  <tr><td>You will get back (wallet)</td><td className="td-amt-in">+ {fmt(preview.you_will_get_back)}</td></tr>
                  <tr><td>Will be deducted</td><td className="td-amt-out">− {fmt(preview.will_be_cut)}</td></tr>
                  {preview.cut_breakdown && (
                    <>
                      <tr><td>→ Professional compensation ({preview.cut_breakdown.professional_compensation.percent}%)</td><td>{fmt(preview.cut_breakdown.professional_compensation.amount)} <span className="muted">{preview.cut_breakdown.professional_compensation.goes_to}</span></td></tr>
                      <tr><td>→ Platform share ({preview.cut_breakdown.platform_share.percent}%)</td><td>{fmt(preview.cut_breakdown.platform_share.amount)}</td></tr>
                    </>
                  )}
                  <tr><td>Trust score impact</td><td>{preview.trust_score_impact}</td></tr>
                </tbody>
              </table>
            ) : (
              <table>
                <tbody>
                  <tr><td>Refund to customer (100%)</td><td className="td-amt-in">+ {fmt(preview.customer_will_get_back)}</td></tr>
                  <tr><td>Your penalty (owed)</td><td className="td-amt-out">− {fmt(preview.your_penalty)}</td></tr>
                  <tr><td>Trust score impact</td><td>{preview.trust_score_impact}</td></tr>
                </tbody>
              </table>
            )}
            <div className="alert warn mt">{preview.message}</div>
            <div className="row mt">
              <button className="btn danger" onClick={onConfirm}>{confirmLabel}</button>
              <button className="btn secondary" onClick={onClose}>No, go back</button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}

// Direction-aware amount cell for ledgers: 'in' (green +) or 'out' (red -)
export function Amt({ value, dir }) {
  const sign = dir === 'in' ? '+' : '−';
  return <span className={dir === 'in' ? 'td-amt-in' : 'td-amt-out'}>{sign} {fmt(value)}</span>;
}

// Horizontal money-flow diagram used in guide/explainer pages
export function MoneyFlow({ nodes }) {
  return (
    <div className="flow">
      {nodes.map((n, i) => (
        <React.Fragment key={i}>
          {i > 0 && <span className="arrow">→</span>}
          <div className="node">
            <b>{n.title}</b>
            {n.sub}
          </div>
        </React.Fragment>
      ))}
    </div>
  );
}

export function Steps({ steps, current }) {
  return (
    <div className="steps">
      {steps.map((s, i) => (
        <div key={s} className={`step ${i < current ? 'done' : i === current ? 'active' : ''}`}>
          {i + 1}. {s}
        </div>
      ))}
    </div>
  );
}

export function Empty({ icon = '📭', children }) {
  return (
    <div className="empty">
      <div className="big">{icon}</div>
      {children}
    </div>
  );
}
